
.INCLUDE "M32DEF.INC"


MAIN:
CONFIG:
       
       .DEF N = R20 ; "N" RETARDOS DE 100uS
	   .DEF A = R21 ; VARIABLE UTILIZADA PARA VARIOS PROPOSITOS
	   .DEF C = R22 ;VARIABLE UTILIZADA COMO CONTADOR DE OVERFLOWS
	   LDI A,255
	   OUT DDRA,A
	   LDI N,1 ;
	   LDI C,0
	   LDI A,0B0000011
	   OUT TCCR0,A ; SETEO CLOCK EN MODO NORMAL Y CON PRESCALADO

	   RCALL RETARDO
	   LDI A,0
	   OUT PORTA,A


RETARDO:
PRE_LOOP:
	  IN A, SREG
	  PUSH A
      LDI A,1
	  OUT TIFR,A ; LIMPIO EL REGISTRO DE INTERRUPCIONES PARA UNA NUEVA LECTURA
	  LDI A,0
	  OUT TCNT0,A ; ABRO EL TIMER EN 0      
LOOP:
	  IN A,TIFR ; OBTENGO EL VALOR DEL REGISTRO DE INTERRUPCIONES	
      SBRS A,0 ; SALTEA LA SIGUIENTE INSTRICCION SI EL BIT 0 (TOV0) ES UN 1
	  RJMP LOOP ; BUCLE HASTA GENERAR 1 OVERFLOW (CONTAR DE 155 A 255 + 1) 
	  INC C ; INCREMENTO EL VALOR DEL CONTADOR
	  CP C,N
	  BRNE PRE_LOOP ; VUELVO AL LOOP SIN EL CONTADOR NO LLEGO A N.
	  POP A
	  OUT SREG,A
	  RET




	  
	




